language: python
dist: trusty
sudo: required
cache: pip
python:
    - 2.7
    - 3.4
    - 3.5
addons:
  apt:
    packages:
    - mysql-server
    - redis-server
    - zookeeper
    - influxdb
    - mongodb
    - etcd
install: pip install tox-travis
script: travis_wait 20 tox -v
# notifications:
#  email:
#    - julien@danjou.info
