language: python
before_script:
  - "elasticsearch --version"
addons:
  apt:
    packages:
    # FIXME(jd) Does not work on Travis?
    # - elasticsearch
    - redis-server
    - redis-sentinel
    - zookeeper
    - influxdb
    - etcd
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pep8
install: pip install tox
script: tox
notifications:
  email:
    - julien@danjou.info
